const MSG = require('../../config/Messages');

module.exports = {
    AWAITING_PAYMENT: MSG.PAYMENT.STATUS.AWAITING_PAYMENT,
    PAID: MSG.PAYMENT.STATUS.PAID,
    CANCELED: MSG.PAYMENT.STATUS.CANCELED,
    EXPIRED: MSG.PAYMENT.STATUS.EXPIRED
}