const MSG = require('../../config/Messages');

module.exports = {
    AWAITING_PAYMENT: MSG.PURCHASE.STATUS.AWAITING_PAYMENT,
    PAID: MSG.PURCHASE.STATUS.PAID,
    CANCELED: MSG.PURCHASE.STATUS.CANCELED,
    SENT: MSG.PURCHASE.STATUS.SENT,
    DELIVERED: MSG.PURCHASE.STATUS.DELIVERED
}